# Generated by Django 4.2.7 on 2023-11-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAnna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pole', models.TextField()),
                ('email', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
