# Generated by Django 4.2.7 on 2023-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_modelegor'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelegor',
            name='img',
            field=models.ImageField(default=1, height_field=100, upload_to='img/', width_field=100),
            preserve_default=False,
        ),
    ]
