# Generated by Django 4.2.7 on 2023-11-28 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_modelegor_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelegor',
            name='img',
            field=models.ImageField(upload_to='imgs'),
        ),
    ]
